apiVersion: v1
kind: Service
metadata:
  name: aramid-follow-mainnet-data-service
  namespace: aramid-relay-mainnet
spec:
  type: ClusterIP
  selector:
    app: aramid-follow-mainnet
  ports:
    - name: algoclient
      protocol: TCP
      appProtocol: http
      port: 28180
      targetPort: 28180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aramid-follow-mainnet-node-1
  namespace: aramid-relay-mainnet
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aramid-follow-mainnet
  template:
    metadata:
      labels:
        app: aramid-follow-mainnet
        lb: aramid-follow-mainnet
    spec:
      nodeName: sch-g-01
      terminationGracePeriodSeconds: 3
      containers:
        - name: aramid-follow-mainnet
          image: scholtz2/aramid-algo-follow-node:v3.25.0-stable
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4000Mi"
              cpu: "2000m"
            limits:
              memory: "20000Mi"
              cpu: "16000m"
          #command: ["/bin/bash", "-ec", "while :; do date; sleep 60 ; done"]
          #command:
          #  - /bin/bash
          #  - /app/run.sh
          # startupProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - /app/health.sh
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   failureThreshold: 1000
          # readinessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - /app/health.sh
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 10
          #   failureThreshold: 100
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - /app/health.sh
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 10
          #   failureThreshold: 6
          #   terminationGracePeriodSeconds: 60

          ports:
            - containerPort: 14160
              protocol: TCP
            - containerPort: 18180
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: aramid-follow-main-vol-root-1
              mountPath: /app/data
            - name: aramid-follow-main-vol-net-1
              mountPath: /app/data/aramidmain-v1.0
            - name: aramid-follow-main-vol-catchpoints-1
              mountPath: /app/data/aramidmain-v1.0/catchpoints
      volumes:
        - name: aramid-follow-main-vol-root-1
          persistentVolumeClaim:
            claimName: aramid-follow-main-vol-root-1
        - name: aramid-follow-main-vol-net-1
          persistentVolumeClaim:
            claimName: aramid-follow-main-vol-net-1
        - name: aramid-follow-main-vol-catchpoints-1
          persistentVolumeClaim:
            claimName: aramid-follow-main-vol-catchpoints-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aramid-follow-main-vol-root-1
  namespace: aramid-relay-mainnet
spec:
  storageClassName: aramid-follow-main-root-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aramid-follow-main-vol-net-1
  namespace: aramid-relay-mainnet
spec:
  storageClassName: aramid-follow-main-net-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aramid-follow-main-vol-catchpoints-1
  namespace: aramid-relay-mainnet
spec:
  storageClassName: aramid-follow-main-catchpoints-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aramid-follow-main-root-1
spec:
  storageClassName: aramid-follow-main-root-1
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/14tb/aramid/mainnet-follow/root"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sch-g-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aramid-follow-main-net-1
spec:
  storageClassName: aramid-follow-main-net-1
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/14tb/aramid/mainnet-follow/net"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sch-g-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aramid-follow-main-catchpoints-1
spec:
  storageClassName: aramid-follow-main-catchpoints-1
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/14tb/aramid/mainnet-follow/catchpoints"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - sch-g-01
