apiVersion: v1
kind: Namespace
metadata:
  name: algo-relay-voitest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relaynode-3
  namespace: algo-relay-voitest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: algo-relay-voitest
  template:
    metadata:
      labels:
        app: algo-relay-voitest
        server: 00-htz-fi-hel-001
    spec:
      nodeName: s3-k1-fi.a-wallet.net
      hostname: 00-htz-fi-hel-001
      terminationGracePeriodSeconds: 3
      containers:
        - name: algo-relay-voitest
          image: scholtz2/algorand-relay-voitest:3.24.0-stable
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "8000Mi"
              cpu: "4000m"
            limits:
              memory: "16000Mi"
              cpu: "16000m"
          command:
            - /bin/bash
            - /app/run.sh
          ports:
            - containerPort: 5011
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
            - containerPort: 28081
              protocol: TCP
          startupProbe:
            exec:
              command:
              - /bin/bash
              - /app/health.sh
            initialDelaySeconds: 10
            periodSeconds: 10   
            failureThreshold: 1000
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - /app/health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10   
            failureThreshold: 100
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - /app/health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10        
            failureThreshold: 6
            terminationGracePeriodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: algo-voitest-vol-root-3
              mountPath: /app/data
            - name: algo-voitest-vol-net-3
              mountPath: /app/data/voitest-v1.0
            - name: algo-voitest-vol-catchpoints-3
              mountPath: /app/data/voitest-v1.0/catchpoints
      volumes:
        - name: algo-voitest-vol-root-3
          persistentVolumeClaim:
            claimName: algo-voitest-vol-root-3
        - name: algo-voitest-vol-net-3
          persistentVolumeClaim:
            claimName: algo-voitest-vol-net-3
        - name: algo-voitest-vol-catchpoints-3
          persistentVolumeClaim:
            claimName: algo-voitest-vol-catchpoints-3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-voitest-vol-root-3
  namespace: algo-relay-voitest
spec:
  storageClassName: algo-voitest-root-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-voitest-vol-net-3
  namespace: algo-relay-voitest
spec:
  storageClassName: algo-voitest-net-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-voitest-vol-catchpoints-3
  namespace: algo-relay-voitest
spec:
  storageClassName: algo-voitest-catchpoints-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: algo-voitest-root-3
spec:
  storageClassName: algo-voitest-root-3
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/algo/voitest/root"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - s3-k1-fi.a-wallet.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: algo-voitest-net-3
spec:
  storageClassName: algo-voitest-net-3
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/algo/voitest/net"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - s3-k1-fi.a-wallet.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: algo-voitest-catchpoints-3
spec:
  storageClassName: algo-voitest-catchpoints-3
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/algo/voitest/catchpoints"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - s3-k1-fi.a-wallet.net