apiVersion: v1
kind: Service
metadata:
  name: algo-set-service
  namespace: algo-relay-mainnet
spec:
  type: NodePort
  selector:
    app: algo-relay-mainnet
  ports:
    - name: algorelay
      protocol: TCP
      appProtocol: http
      port: 4160
      nodePort: 4160
      targetPort: 4160
---
apiVersion: v1
kind: Service
metadata:
  name: algo-set-service-data
  namespace: algo-relay-mainnet
spec:
  type: ClusterIP
  selector:
    app: algo-relay-mainnet
  ports:
    - name: algoclient
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: algo-set-service-9100
  namespace: algo-relay-mainnet
spec:
  type: NodePort
  selector:
    app: algo-relay-mainnet
  ports:
    - name: algorelay
      protocol: TCP
      appProtocol: http
      port: 9100
      nodePort: 9100
      targetPort: 9100
