apiVersion: v1
kind: Namespace
metadata:
  name: algo-relay-mainnet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relaynode-5
  namespace: algo-relay-mainnet
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: algo-relay-mainnet-nonarchival
  template:
    metadata:
      labels:
        app: algo-relay-mainnet-nonarchival
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 3
      containers:
        - name: algo-relay-mainnet-nonarchival
          image: scholtz2/algorand-relay-mainnet:4.0.1-stable
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            limits:
              memory: "28000Mi"
              cpu: "15000m"
          command:
            - /bin/bash
            - /app/run.sh
          #command: ["/bin/bash", "-ec", "while :; do date; sleep 60 ; done"]
          ports:
            - containerPort: 4160
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          startupProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
            terminationGracePeriodSeconds: 60
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: algo-mainnet-vol-root-5
              mountPath: /app/data
            - name: algo-mainnet-vol-net-5
              mountPath: /app/data/mainnet-v1.0
      volumes:
        - name: algo-mainnet-vol-root-5
          persistentVolumeClaim:
            claimName: algo-mainnet-vol-root-5
        - name: algo-mainnet-vol-net-5
          persistentVolumeClaim:
            claimName: algo-mainnet-vol-net-5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-mainnet-vol-root-5
  namespace: algo-relay-mainnet
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-mainnet-vol-net-5
  namespace: algo-relay-mainnet
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
