{{- if .Values.ingressParticipationNode.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.prefix }}{{ .Values.ingressParticipationNode.name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
    cert-manager.io/cluster-issuer: {{ .Values.ingressParticipationNode.metadata.annotations.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '{{ .Values.ingressParticipationNode.metadata.annotations.timeout }}'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '{{ .Values.ingressParticipationNode.metadata.annotations.timeout }}'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '{{ .Values.ingressParticipationNode.metadata.annotations.timeout }}'
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ .Values.ingressParticipationNode.host }}
      secretName: tls-{{ .Values.ingressParticipationNode.host }}
  rules:
    - host: {{ .Values.ingressParticipationNode.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.prefix }}{{ .Values.service18888.name }}
                port:
                  number: 18888
{{- end }}
