apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}{{ .Values.service18888.name }}
spec:
  type: ClusterIP
  selector:
    {{ .Values.deploymentParticipationNode.label.key }}: {{ .Values.prefix }}{{ .Values.deploymentParticipationNode.label.value }}
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: {{ .Values.service18888.port.service }}
      {{- if and (or (eq .Values.service18888.type "NodePort") (eq .Values.service18888.type "LoadBalancer")) (not (empty .Values.service18888.port.node)) }}
      nodePort: {{ .Values.service18888.port.node }}
      {{- end }}
      targetPort: {{ .Values.service18888.port.target }}
