apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}{{ .Values.pvcRoot.name }}
spec:
  storageClassName: {{ .Values.pvcRoot.storageClassName }}
  accessModes:
    - {{ .Values.pvcRoot.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvcRoot.resources.requests.storage }}