FROM ubuntu:latest as build
USER root
ENV ARCH=amd64
ARG ALGO_VER
RUN apt update && apt dist-upgrade -y
ENV DEBIAN_FRONTEND noninteractive
RUN apt install -y mc wget telnet git make  gcc build-essential aptly awscli binutils build-essential curl gnupg2 libboost-all-dev sqlite3 autoconf jq bsdmainutils shellcheck
ENV GOPATH=/usr/local/algo
ENV GOROOT=/usr/local/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH
ENV GOPROXY=https://proxy.golang.org,https://pkg.go.dev,https://goproxy.io,direct
RUN wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz && rm -rf $GOPATH && tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz && go version
RUN git clone https://github.com/algorand/go-algorand && cd go-algorand && git checkout $ALGO_VER
WORKDIR /go-algorand
RUN ./scripts/configure_dev.sh
RUN ./scripts/buildtools/install_buildtools.sh
RUN ls -lA
RUN make
#RUN make test
#RUN make integration
#RUN make fmt
#RUN make lint
#RUN make fix
#RUN make vet
#RUN make sanity

FROM ubuntu:latest as final
USER root
RUN apt update && apt dist-upgrade -y
ENV DEBIAN_FRONTEND noninteractive
RUN apt install -y mc wget telnet git curl
COPY --from=build /usr/local/algo/bin /usr/local/algo/bin
ENV GOPATH=/usr/local/algo
ENV ALGORAND_DATA=/app/data
RUN mkdir /app
RUN mkdir /app/data
RUN mkdir /app/mainnet
COPY --from=build /go-algorand/installer/genesis/mainnet/genesis.json /app/mainnet/genesis.json
ENV PATH=$GOPATH/bin:$PATH
WORKDIR /app
RUN echo 3
COPY . . 
RUN useradd -ms /bin/bash algo
RUN chown algo:algo /app -R
USER algo
CMD ["/bin/bash"]


