# to debug see for example https://developer.algorand.org/tutorials/using-the-teal-debugger-to-debug-a-smart-contract/#1-deploying-the-smart-contract
# at point: tealdbg debug approval_program.teal -d dr.msgp --group-index 1
# use: tealdbg debug approval_program.teal --listen 0.0.0.0 -d dr.msgp --group-index 1
# copy from to the browser (replace 0.0.0.0 with 127.0.0.1): devtools://devtools/bundled/js_app.html?experiments=true&v8only=false&ws=127.0.0.1:9392/3184c28d85e22e04b7989afb6a21fd9f67dc6d3054c2ca15133775bbd68797a0
---
apiVersion: v1
kind: Service
metadata:
  name: algo-participation-algod-sandbox
  namespace: algo-sandbox
spec:
  type: NodePort
  selector:
    app: algo-participation-sandbox
  ports:
    - name: algoclient
      protocol: TCP
      appProtocol: http
      port: 9392
      targetPort: 9392
      nodePort: 9392