{{- if .Values.pvConduit.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix }}{{ .Values.pvConduit.name }}
spec:
  {{- if .Values.nodeName }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nodeName }}
  {{- end }}
  storageClassName: {{ .Values.pvcConduit.storageClassName }}
  capacity:
    storage: {{ .Values.pvcConduit.resources.requests.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pvConduit.hostPath }}
{{- end }}