apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}{{ .Values.secretConduit.name }}
type: Opaque
stringData:
  conduit.yml: |
    # Log verbosity: PANIC, FATAL, ERROR, WARN, INFO, DEBUG, TRACE
    log-level: INFO
    retry-count: 10
    retry-delay: "1s"
    hide-banner: false
    
    api:
      addr: ":8981"
    
    metrics:
      mode: OFF
      addr: ":9999"
      prefix: "conduit"
    
    importer:
      name: algod
      config:
        mode: "follower"
        netaddr: "http://{{ .Values.prefix }}{{ .Values.serviceFollowerNode.name }}:8080"
        token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        catchup-config:
          admin-token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    
    processors:
    
    exporter:
      name: postgresql
      config:
        connection-string: {{ printf "host=%s%s port=5432 user=%s password=%s dbname=%s sslmode=disable" .Values.prefix .Values.serviceDB.name .Values.db.user .Values.db.password .Values.db.dbName   | quote  }}
        max-conn: 20