apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}{{ .Values.secretIndexer.name }}
type: Opaque
data:
  INDEXER_ALGOD_TOKEN: {{ .Values.secretIndexer.algodToken | b64enc | quote }}
  INDEXER_API_TOKEN: {{ .Values.secretIndexer.indexerToken | b64enc | quote }}
  INDEXER_POSTGRES_CONNECTION_STRING:
    {{ printf "host=%s%s port=5432 user=%s password=%s dbname=%s sslmode=disable" .Values.prefix .Values.serviceDB.name .Values.secretIndexer.dbUser .Values.secretIndexer.dbPassword .Values.secretIndexer.dbName  | b64enc | quote  }}
  POSTGRES_DB: {{ .Values.secretIndexer.dbName | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secretIndexer.dbPassword | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secretIndexer.dbUser | b64enc | quote }}
