apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}{{ .Values.serviceDB.name }}
spec:
  type: {{ .Values.serviceDB.type }}
  selector:
    {{ .Values.deploymentDB.label.key }}: {{ .Values.prefix }}{{ .Values.deploymentDB.label.value }}
  ports:
    - name: algod-port
      protocol: TCP
      appProtocol: http
      port: {{ .Values.serviceDB.port.service }}
      {{- if and (or (eq .Values.serviceDB.type "NodePort") (eq .Values.serviceDB.type "LoadBalancer")) (not (empty .Values.serviceDB.port.node)) }}
      nodePort: {{ .Values.serviceDB.port.node }}
      {{- end }}
      targetPort: {{ .Values.serviceDB.port.target }}
