pvcRoot:
  storageClassName: "nfs-fast-retain"
    
deployment:
  resources:
    requests:
      memory: '1000Mi'
      cpu: '1000m'
    limits:
      memory: '16000Mi'
      cpu: '8000m'

serviceAVMProtocol:
  type: 'NodePort'
  port: 
    node: 14160
