apiVersion: v1
kind: Namespace
metadata:
  name: aramid-relay-mainnet
---
apiVersion: v1
kind: Service
metadata:
  name: aramid-set-service
  namespace: aramid-relay-mainnet
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer for AWS
  selector:
    app: aramid-relay-mainnet
  ports:
    - name: algorelay
      protocol: TCP
      appProtocol: http
      port: 14160
      targetPort: 14160
---
apiVersion: v1
kind: Service
metadata:
  name: aramid-set-service-data
  namespace: aramid-relay-mainnet
spec:
  type: ClusterIP
  selector:
    app: aramid-relay-mainnet
  ports:
    - name: algoclient
      protocol: TCP
      appProtocol: http
      port: 18180
      targetPort: 18180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relaynode-1
  namespace: aramid-relay-mainnet
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aramid-relay-mainnet
  template:
    metadata:
      labels:
        app: aramid-relay-mainnet
        lb: aramid-relay-mainnet
    spec:
      # Removed nodeName specification
      terminationGracePeriodSeconds: 3
      containers:
        - name: aramid-relay-mainnet
          image: scholtz2/aramid-algo-node:v4.0.2-stable
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '4000Mi'
              cpu: '2000m'
            limits:
              memory: '20000Mi'
              cpu: '16000m'
          startupProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 1000
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 100
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
            terminationGracePeriodSeconds: 60
          ports:
            - containerPort: 14160
              protocol: TCP
            - containerPort: 18180
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: aramid-main-vol-root-1
              mountPath: /app/data
            - name: aramid-main-vol-net-1
              mountPath: /app/data/aramidmain-v1.0
            - name: aramid-main-vol-catchpoints-1
              mountPath: /app/data/aramidmain-v1.0/catchpoints
      volumes:
        - name: aramid-main-vol-root-1
          persistentVolumeClaim:
            claimName: aramid-main-vol-root-1
        - name: aramid-main-vol-net-1
          persistentVolumeClaim:
            claimName: aramid-main-vol-net-1
        - name: aramid-main-vol-catchpoints-1
          persistentVolumeClaim:
            claimName: aramid-main-vol-catchpoints-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aramid-main-vol-root-1
  namespace: aramid-relay-mainnet
spec:
  storageClassName: gp2  # Changed to AWS EBS storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aramid-main-vol-net-1
  namespace: aramid-relay-mainnet
spec:
  storageClassName: gp2  # Changed to AWS EBS storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aramid-main-vol-catchpoints-1
  namespace: aramid-relay-mainnet
spec:
  storageClassName: gp2  # Changed to AWS EBS storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

# Removed PersistentVolume definitions as AWS EKS will dynamically provision volumes