apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}{{ .Values.service28081.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.prefix }}algo-participation-aramidmain
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: {{ .Values.service28081.port.service }}
      {{- if and (or (eq .Values.service28081.type "NodePort") (eq .Values.service28081.type "LoadBalancer")) (not (empty .Values.service28081.port.node)) }}
      nodePort: {{ .Values.service28081.port.node }}
      {{- end }}
      targetPort: {{ .Values.service28081.port.target }}
