apiVersion: v1
kind: Namespace
metadata:
  name: aramid-indexer-mainnet
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: aramid-indexer-mainnet
  namespace: aramid-indexer-mainnet
spec:
  selector:
    matchLabels:
      app: aramid-indexer-mainnet
  replicas: 1
  template:
    metadata:
      labels:
        app: aramid-indexer-mainnet
    spec:
      containers:
      - name: aramid-indexer-mainnet
        image: scholtz2/algorand-indexer:2.11.1-stable
        imagePullPolicy: Always
        command: ["/bin/bash"]  
        args: ["-c", "./run.sh" ]   
        ports:
            - containerPort: 8980
              protocol: TCP
        readinessProbe:
            tcpSocket:
              port: 8980
            initialDelaySeconds: 10
            timeoutSeconds: 5  
            failureThreshold: 2
        livenessProbe:
            tcpSocket:
              port: 8980
            initialDelaySeconds: 20
            timeoutSeconds: 5  
            failureThreshold: 2
            terminationGracePeriodSeconds: 1
        env:
        - name: INDEXER_POSTGRES_CONNECTION_STRING
          value: "host=.. port=5432 user=.. password=.. dbname=.. sslmode=disable"
        - name: INDEXER_ALGOD_ADDRESS
          value: "algo-set-service-data.algo-relay-mainnet:8080"
        - name: INDEXER_ALGOD_TOKEN
          value: ".."
        - name: INDEXER_API_TOKEN
          value: ".."
        - name: INDEXER_DEV_MODE
          value: "0"
        - name: INDEXER_METRICS_MODE
          value: "1"
        - name: INDEXER_GENESIS
          value: "/app/genesis/aramidmain/genesis.json"