apiVersion: v1
kind: Namespace
metadata:
  name: aramid-indexer-mainnet
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: postgres-secret-aramidmain-indexer
#  namespace: aramid-indexer-mainnet
#type: Opaque
#stringData:
#  superUserPassword: verystrongpassword
#  replicationUserPassword: verystrongpassword
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: kubegres-aramid
  namespace: aramid-indexer-mainnet

spec:
   replicas: 1
   image: postgres:14.1

   database:
      size: 200Mi
      storageClassName: nfs-fast-retain-h2
   securityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: false
   scheduler:
       affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sch-h-02
              topologyKey: kubernetes.io/hostname
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret-aramidmain-indexer
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret-aramidmain-indexer
              key: replicationUserPassword
