apiVersion: v1
entries:
  aramid-indexer:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:06:48.072533205+01:00"
    description: Aramid indexer node for aramidmain-1.0 blockchain.
    digest: 3ef1ad721ff5f5cdfd2e8627ced170f01d9abe38a755279cc6e23b1523924083
    name: aramid-indexer
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-indexer-1.0.0.tgz
    version: 1.0.0
  aramid-participation:
  - apiVersion: v2
    appVersion: 3.26.0
    created: "2024-10-28T12:06:48.072992666+01:00"
    description: Aramid participation node for aramidmain-1.0 blockchain.
    digest: 67256fb6dfca7ad9aff4269be3ec0edd063d41037d41ebd658eda11bf7802569
    name: aramid-participation
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-participation-3.26.0.tgz
    version: 3.26.0
  aramid-relay:
  - apiVersion: v2
    appVersion: 3.26.0
    created: "2024-10-28T12:06:48.092896638+01:00"
    description: Aramid relay node for aramidmain-1.0 blockchain.
    digest: 48139c917dd02332861398545302595104a05f87e8efb77fb7255a5400f9423b
    name: aramid-relay
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-relay-3.26.0.tgz
    version: 3.26.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:06:48.092363159+01:00"
    description: Aramid relay node for aramidmain-1.0 blockchain.
    digest: eb7a63bbe415fb80a3a8a107053f05290d4fa5bb1dae6c4bb17eb029dcf0d30e
    name: aramid-relay
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-relay-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:06:48.092024144+01:00"
    description: Aramid relay node for aramidmain-1.0 blockchain.
    digest: 2e7c21c8ff48ca2c9a8b75837680b1622cbdad5fb190e018a9c96023e0c39268
    name: aramid-relay
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-relay-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:06:48.091691952+01:00"
    description: Aramid relay node for aramidmain-1.0 blockchain.
    digest: 2610602c38475043956b746d363d30964b689abebc87953ab8663f8be5932eb4
    name: aramid-relay
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-relay-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:06:48.089366887+01:00"
    description: Aramid relay node for aramidmain-1.0 blockchain.
    digest: 00676d6bbc23f749ddf36759597db1d834fd6ce394e82d6f1d7c3492f77815d0
    name: aramid-relay
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-relay-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:06:48.073414546+01:00"
    description: Aramid relay node for aramidmain-1.0 blockchain.
    digest: 3891a4c8484efc7a2579bd5cc19fd99ff8fba2677ab35f40f3466a1b125de318
    name: aramid-relay
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/aramid-relay-1.0.0.tgz
    version: 1.0.0
  voimain-participation:
  - apiVersion: v2
    appVersion: 3.26.0
    created: "2024-10-28T12:06:48.093670898+01:00"
    description: VOI participation node for voimain-1.0 blockchain.
    digest: b1f50493a073380741026b4a893e893fb4ba37b95f40a53ed941067197cba2e0
    name: voimain-participation
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/voimain-participation-3.26.1.tgz
    version: 3.26.1
  - apiVersion: v2
    appVersion: 3.26.0
    created: "2024-10-28T12:06:48.093256061+01:00"
    description: VOI participation node for voimain-1.0 blockchain.
    digest: ae7992b8bc389facda2a5cb0468d70d5019ad863c8cb8bdeb319c87ce3127848
    name: voimain-participation
    type: application
    urls:
    - https://scholtz.github.io/AlgorandNodes/helm/voimain-participation-3.26.0.tgz
    version: 3.26.0
generated: "2024-10-28T12:06:48.07129198+01:00"
