apiVersion: v1
kind: Service
metadata:
  name: algo-set-service-lb
  namespace: algorand
spec:
  type: NodePort
  selector:
    app: relaynode-app-ss
  ports:
    - name: algorelay
      protocol: TCP
      appProtocol: http
      port: 4160
      nodePort: 30000
      targetPort: 4160