apiVersion: apps/v1 
kind: Deployment
metadata:
  name: algorand-indexer
  namespace: algorand-indexer-testnet
spec:
  selector:
    matchLabels:
      app: algorand-indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: algorand-indexer
    spec:
      containers:
      - name: algorand-indexer
        image: scholtz2/algorand-indexer:v3.5.0-stable
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
            - name: algorand-indexer-conf
              mountPath: /app/indexer.yaml
              subPath: indexer.yaml
      volumes:
        - name: algorand-indexer-conf
          configMap:
            name: algorand-indexer-conf