apiVersion: v1
kind: Namespace
metadata:
  name: algo-relay-voimain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relaynode-1
  namespace: algo-relay-voimain
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: algo-relay-voimain-nonarchival
  template:
    metadata:
      labels:
        app: algo-relay-voimain-nonarchival
        appId: 00-lin-in-bom-001
    spec:
      hostname: 00-lin-in-bom-001
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 3
      containers:
        - name: algo-relay-voimain-nonarchival
          image: scholtz2/algorand-relay-voimain:4.0.1-stable
          imagePullPolicy: Always
          resources:
            requests:
              memory: '1000Mi'
              cpu: '1000m'
            limits:
              memory: '8000Mi'
              cpu: '8000m'
          command:
            - /bin/bash
            - /app/run.sh
          # command: ["/bin/bash", "-ec", "while :; do date; sleep 60 ; done"]
          ports:
            - containerPort: 5011
              protocol: TCP
            - containerPort: 28081
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
          startupProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1000
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 1
            timeoutSeconds: 10
            failureThreshold: 100
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /app/health.sh
            initialDelaySeconds: 1
            timeoutSeconds: 10
            failureThreshold: 6
            terminationGracePeriodSeconds: 60
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: algo-voimain-vol-root-1
              mountPath: /app/data
            - name: algo-voimain-vol-net-1
              mountPath: /app/data/voimain-v1
            - name: algo-voimain-vol-catchpoints-1
              mountPath: /app/data/voimain-v1/catchpoints
      volumes:
        - name: algo-voimain-vol-root-1
          persistentVolumeClaim:
            claimName: algo-voimain-vol-root-1
        - name: algo-voimain-vol-net-1
          persistentVolumeClaim:
            claimName: algo-voimain-vol-net-1
        - name: algo-voimain-vol-catchpoints-1
          persistentVolumeClaim:
            claimName: algo-voimain-vol-catchpoints-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-voimain-vol-root-1
  namespace: algo-relay-voimain
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-voimain-vol-net-1
  namespace: algo-relay-voimain
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algo-voimain-vol-catchpoints-1
  namespace: algo-relay-voimain
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
