apiVersion: apps/v1 
kind: Deployment
metadata:
  name: algorand-indexer
  namespace: algorand-indexer
spec:
  selector:
    matchLabels:
      app: algorand-indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: algorand-indexer
    spec:
      containers:
      - name: algorand-indexer
        image: scholtz2/algorand-indexer:2.8.0-stable
        env:
        - name: PG_CONN_STR
          value: "host=localhost port=5432 user=algo password=indexerDbPass dbname=ledgerdb sslmode=disable"
        - name: ALGOD_HOST
          value: "http://algo-set-service.algorand-testnet:4161"
        - name: ALGOD_TOKEN
          value: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"